version: "3"
services:
    
    flask-test-basic-app:
        image: jstnck/flask-test-basic-app
        container_name: flask-test-basic-app
        restart: always
        environment:
            - APP_NAME=MyFlaskApp
        expose:
            - 8080         
            
    postgres:
        image: jstnck/bball-api_postgres
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
    
    
    nginx:
        image: jstnck/bball-api_nginx
        container_name: nginx
        restart: always
        ports:
            - "8080:80"