version: "3"
services:
    
    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment:
            DATABASE_URL: postgresql://postgres:admin@postgres:5432/postgres
        expose:
            - 8080    


    postgres:
        build: ./postgres
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: postgres
            POSTGRES_HOST_AUTH_METHOD: md5

        expose:
            - 5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8888:8080
        links:
            - postgres:postgres
    
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "8080:80"